spring:
  profiles:
    active: prod
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost:1433;DatabaseName=fkdb
    username: sa
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database: sql_server
    database-platform: org.hibernate.dialect.SQLServer2008Dialect
server:
  port: 8080
  servlet:
    context-path: /fk
