spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://192.168.5.231:1433;DatabaseName=fkdb
    username: fkuser
    password: FKuser730*
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database: sql_server
    database-platform: org.hibernate.dialect.SQLServer2008Dialect
server:
  port: 8080
  servlet:
    context-path: /fk
